### ISSUE TITLE
macOS 10.15.3 breaks the fix.

### ISSUE THREAD

**Issue by TheElectroclassics** [thenickdude/wacom-driver-fix#1]

**Comment by thenickdude** [comment]
Did you upgrade to 10.15.3 and have macOS remove the Wacom settings pane, like I did? I reinstalled the fix and everything is fine for me now.

There's a new .pkg-based installer linked in the Automatic Method section of the readme now that installs the entire fixed driver from scratch, so use that one.

**Comment by TheElectroclassics** [comment]
>Did your upgrade to 10.15.3 trigger macOS to remove the Wacom settings pane, like happened to me?
Yes, I'll try with the reinstall then.

**Comment by TheElectroclassics** [comment]
Reinstalling fixes it. Thank you!
