### ISSUE TITLE
Menu Icon in Dark Mode doesn't appear

### ISSUE THREAD

**Issue by allejo** [thenickdude/wacom-driver-fix#10]
First of all, thank you so much for this patch! 🎉

Now for the actual issue. This isn't a problem with this specific patch. It's been a problem since I can remember. I was wondering if a fix could be incorporated into this repo that fixes the menu icon in dark mode?

**Dark Mode when monitor is active**

![Screen Shot 2020-03-31 at 3 08 15 PM](https://user-images.githubusercontent.com/1246453/78079696-7d558500-7361-11ea-930b-783712fd026a.png)

**Dark mode when _another_ monitor is active**

![Screen Shot 2020-03-31 at 3 08 08 PM](https://user-images.githubusercontent.com/1246453/78079699-7e86b200-7361-11ea-9d06-6b2faac8807b.png)

**Light mode when monitor is active**

![Screen Shot 2020-03-31 at 3 09 23 PM](https://user-images.githubusercontent.com/1246453/78079751-a249f800-7361-11ea-8a41-dd6aebfb77e7.png)

**Light mode when _another_ monitor is active**

![Screen Shot 2020-03-31 at 3 09 17 PM](https://user-images.githubusercontent.com/1246453/78079748-a1b16180-7361-11ea-8a4e-f9409c82f4e8.png)

**Comment by thenickdude** [comment]
Which driver and tablet is that, is it a Cintiq? There doesn't seem to be any tray icon system for Bamboo tablets (or Intuos 3 as far as I know).

**Comment by allejo** [comment]
Tablet: Wacom Bamboo Capture Pen and Touch Tablet (CTH470)
Driver: Install-Wacom-Tablet-5.3.7-6-patched.pkg

**Comment by thenickdude** [comment]
Can you show a screenshot of what that icon looks like when you click it? Is there an About menu there which shows a version number or product name? I've never seen this icon before.

**Comment by allejo** [comment]
![image](https://user-images.githubusercontent.com/1246453/78081213-dd015f80-7364-11ea-9974-9351c98161e5.png)
![image](https://user-images.githubusercontent.com/1246453/78081509-8f392700-7365-11ea-9423-1453081c0421.png)
![image](https://user-images.githubusercontent.com/1246453/78081528-9b24e900-7365-11ea-8c60-c04d6c69cc9f.png)

**This icon shows up correctly when a tablet is connected**

![image](https://user-images.githubusercontent.com/1246453/78081543-a2e48d80-7365-11ea-832e-4970f9014b73.png)

**Comment by thenickdude** [comment]
Ahh, I think this is a battery status icon that only appears for tablets with wireless connections, which is why I've never seen it. I'll look into it, but if it's at all difficult then I imagine it won't be worthwhile trying to patch this.

**Comment by allejo** [comment]
Oh yea, it's no big deal if this is more trouble than it's worth. This is more so if it's a quick enough fix, that'd be awesome to have the icon fixed. Otherwise, no big deal :smile:

Thanks for looking into this!

**Comment by thenickdude** [comment]
<img width="166" alt="Screen Shot 2020-04-01 at 1 24 44 PM" src="https://user-images.githubusercontent.com/1921411/78087028-2b256a00-741c-11ea-9463-ea6a13d77364.png">

Hmm I tricked the driver into thinking I had a wireless tablet, and the icon actually shows correctly for me on dark mode. Maybe it doesn't work if your computer changes to dark mode after boot? Try rebooting it if so.

**Comment by allejo** [comment]
> Edit: Oh does this only happen when the tablet is disconnected? I wasn't able to simulate that here yet

Yea, it only happens when the tablet is disconnected. This behavior has persisted through reboots 😞

**Comment by thenickdude** [comment]
My guess here is that because Wacom's "disabled" icon is grey, macOS can't automatically invert the colours of it to match the dark theme. I'm not going to fix this one because it looks like a pain in the ass, but thanks for the suggestion anyway because it was interesting to discover this tray icon existed at all lol.

**Comment by allejo** [comment]
It's all good, thanks for taking a look!
