### ISSUE TITLE
Preferences crash persist even after applying fix

### ISSUE THREAD

**Issue by LeoTals** [thenickdude/wacom-driver-fix#17]
Hi, it seems the Intuos 3 bug of crashing the settings didn't go away with the fix. Can you recommend any other steps?

**Comment by thenickdude** [comment]
Just to clarify, do you mean the bug where it crashes as soon as you click on anything in the settings menu? Or do you mean that you're getting an error message before the settings even load?

Did you install the automatic installer-based version of the fix? That's the one I'd recommend. 

Also make sure you followed the instructions to remove all the permissions from the Privacy page using the minus button and restart the machine and re-tick the permissions afterwards, this fixes most issues.

**Comment by LeoTals** [comment]
The former of the two. I finally got it to work after multiple reinstalls and clearing the perms a good 3 times. Solid work with this patch, thank you.
