### ISSUE TITLE
Didn't work for me HELP 

### ISSUE THREAD

**Issue by arralee** [thenickdude/wacom-driver-fix#21]
So I did all the steps and my Wacom still doesn't align with my screen, the cursor moves but that's what it did usually. Please help, I've seen people say this works

**Comment by thenickdude** [comment]
Which tablet model do you have (check the sticker on the back). Are you getting an error when visiting the Wacom Tablet icon in the System Preferences?

**Comment by arralee** [comment]
I have a CTL-460
yeah I get this error
<img width="636" alt="Screen Shot 2020-05-18 at 5 15 14 PM" src="https://user-images.githubusercontent.com/65568977/82260374-244eaa00-992b-11ea-9b15-46bbd1ab3071.png">

**Comment by arralee** [comment]
Wait, I think it just worked

**Comment by arralee** [comment]
Anyway thank you so much for making this, it suddenly just worked!!

**Comment by thenickdude** [comment]
Magic!
