### ISSUE TITLE
Pentable Preference panel got disabled on 10.15.5

### ISSUE THREAD

**Issue by ringods** [thenickdude/wacom-driver-fix#23]
I got my Wacom Bamboo working again on MacOS 10.15.4 with your fixed driver which I bumped into quite recently.

This morning, I upgraded my system to 10.15.5 and at first boot after the upgrade process, the system told me it disabled the Pentablet Preference pane as it is incompatible with this version of the OS.

What is needed to get this working again on 10.15.5?

**Comment by thenickdude** [comment]
It seems this will happen with every upgrade, but re-running my installer fixes it.
