### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by aluppi46** [thenickdude/wacom-driver-fix#26]
Good evening! I have a wacom CTH 461, I use catalina 10.15.5 and I tried several times step by step to install the drive and I couldn't. The image below shows the error it gives. Thank you!
![Screen Shot 2020-06-18 at 23 09 50](https://user-images.githubusercontent.com/67132577/85089851-0be7de80-b1ba-11ea-9051-e8f62c0106f3.png)

**Comment by thenickdude** [comment]
Hi there,

Did you follow the instructions in this section to first remove all permissions, then reboot and re-tick the entries that reappear?

https://github.com/thenickdude/wacom-driver-fix#fix-up-the-tablet-permissions

This solves most problems. If that didn't fix it, try opening the "Terminal" app, and paste this in and press enter to execute it:

```bash
launchctl load -w /Library/LaunchAgents/com.wacom.*
```

Then reboot your computer and see if it starts working.

**Comment by aluppi46** [comment]
Good Morning! Thanks for the quick response. Unfortunately I did all the steps and it didn't work. The same message appears when I click on the wacom icon in the system preferences. The PenTabletDriver, WacomTabletDriver TabletDriver or WacomTabletSpringboard entries do not appear to select, the same goes for the input monitoring. I'm installing the file you provided with the bamboo plugged into the usb, that's how it is. After writing in the terminal launchctl load -w /Library/LaunchAgents/com.wacom.* the image below shows the result, ams still does not work. Anything else I can do?
![Screen Shot 2020-06-19 at 10 26 48](https://user-images.githubusercontent.com/67132577/85139808-11c1dc00-b21b-11ea-9be8-279f0bd7a4e9.png)

![Screen Shot 2020-06-19 at 10 33 02](https://user-images.githubusercontent.com/67132577/85139657-053d8380-b21b-11ea-857c-54687035c77f.png)
![Screen Shot 2020-06-19 at 10 32 17](https://user-images.githubusercontent.com/67132577/85139770-0e2e5500-b21b-11ea-877b-00a0cb8b1c3e.png)
![Screen Shot 2020-06-19 at 10 27 03](https://user-images.githubusercontent.com/67132577/85139774-0ec6eb80-b21b-11ea-8d1c-147941caa0ce.png)
![Screen Shot 2020-06-19 at 10 26 57](https://user-images.githubusercontent.com/67132577/85139792-0ff81880-b21b-11ea-9c25-98f67e649b2d.png)

**Comment by aluppi46** [comment]
Now it worked!!! Thank you. I opened the Wacom Utility.app in the applications, hit the remove button and the screen below appeared. When clicking on the bamboo with your finger and the pen, the entries appeared to enable them. The screens below follow. Thank you!

![Screen Shot 2020-06-19 at 11 02 59](https://user-images.githubusercontent.com/67132577/85141329-ff48a200-b21c-11ea-9857-1b67f17366c5.png)
![Screen Shot 2020-06-19 at 11 02 57](https://user-images.githubusercontent.com/67132577/85141343-02dc2900-b21d-11ea-8a6b-0702939408e5.png)
![Screen Shot 2020-06-19 at 11 01 20](https://user-images.githubusercontent.com/67132577/85141346-0374bf80-b21d-11ea-9d8f-6485d336f60b.png)
![Screen Shot 2020-06-19 at 11 00 40](https://user-images.githubusercontent.com/67132577/85141348-04a5ec80-b21d-11ea-93e3-24013ab541d6.png)
![Screen Shot 2020-06-19 at 11 00 08](https://user-images.githubusercontent.com/67132577/85141352-05d71980-b21d-11ea-9f8c-d12298b54915.png)

**Comment by thenickdude** [comment]
Ah great, so the problem was caused by the preferences, that's good to know!
