### ISSUE TITLE
I don't get the permission prompts

### ISSUE THREAD

**Issue by dapetcu21** [thenickdude/wacom-driver-fix#30]
Hi! I don't get the permission prompts, with either the unpatched driver or your driver. Additionally, I noticed that your driver doesn't install anything to my `/Library/Extensions`. And if I unpack the `.pkg` with `unpkg.app`, the kernel extensions aren't there. I tried installing the original driver (which does indeed install some kexts) and following the manual patching guide, but I get no permissions prompts either with that method as well. I'm several reboots in. My tablet is a CTE-640.

**Comment by thenickdude** [comment]
These Wacom tablets don't need kernel extensions (thankfully!), it's a user-mode program that is installed to /Library/Application Support/Tablet.

Sorry, CTE-640 (Graphire 4) isn't supported by my driver.

**Comment by dapetcu21** [comment]
Oh. My bad. I confused it with the CTE-460 in your supported list. Thanks

**Comment by thenickdude** [comment]
Graphire 4 is now supported by my latest driver release, please give it a try!

**Comment by dapetcu21** [comment]
This is awesome. Unfortunately, I don't have the tablet anymore, so can't test it.

**Comment by thenickdude** [comment]
Oh well! 🤣
