### ISSUE TITLE
Big Sur?

### ISSUE THREAD

**Issue by HFTobeason** [thenickdude/wacom-driver-fix#36]
Should it work?

**Comment by thenickdude** [comment]
Hi there,

I've tested the Bamboo driver on Big Sur Beta 3 and it worked with no changes. It's likely that all the drivers will continue to work on Big Sur retail.

**Comment by HFTobeason** [comment]
Thanks.  I'll try it on the next public beta - the public beta I'm on right now [11.0 Beta (20A5343j)] is just a wee bit too wonky...

**Comment by thenickdude** [comment]
I've now released updated drivers for Big Sur compatibility, let me know if you have any issues with the new ones.

**Comment by HFTobeason** [comment]
Thank you, Nicholas.  I’ll report when I have a chance to test.
