### ISSUE TITLE
Testing on GD-0608-D macos 10.13.6

### ISSUE THREAD

**Issue by FRAMCHEZ** [thenickdude/wacom-driver-fix#37]
Tested full installer, works great by now, thanks a lot.
Trick I learned from https://apple.stackexchange.com
Worked up to 10.13.4, then Apple remove the "change to 32-bits on application's info panel".

How worked for me. Sierra 10.12.6 Intuos GD-0608-U. Clean installation driver 6.2.0w4 Go /Library/PreferencePanes, move to desktop WacomTablet.prefpane, open package (I use Pacifist on demo) and extract Info.plist, trash this WacomTablet.prefpane From driver 6.3.15-3, open installer package (Pacifist again) DO NOT INSTALL, open package, copy to desktop WacomTablet.prefpane, open package, change the Info.plist (with the one from 6.2.0w4). Close all. Put this prefpane in /Library/PreferencePanes. I set System Preferences.app to 32bit with info, before open Preferences, is working, close and set off 32bit. Summary: Is a 6.2.0w4 installation with a preferences panel from 6.3.15-3 which has inside an Info.plist from 6.2.0w4. This works so did not try any other version of the driver.
NOTE: whats different for me, is that all information is about a newest driver with and oldest PrefPane, that did not worked for me. The last driver for Intuos (GD series) is 6.2.0w4 and did not work on osX 10.12.6, so use that oldest driver installation, but with a newest PrefPane from 6.3.15-3 with inside the info.plist from 6.2.0w4. And you get a full functional System Preferences Panel, don't need old preferences file.

Again, looks great by now, regards.

**Comment by thenickdude** [comment]
Thanks for the testing! Is that the GD-0608-R serial tablet or is there another tablet version I didn't know about?
