### ISSUE TITLE
Intuos 3 crash when editing Tablet Area Mapping fields using keyboard

### ISSUE THREAD

**Issue by yucelyilmazvfx** [thenickdude/wacom-driver-fix#49]
Thanks for making our pen tablets are usable again!

My Intuos 3 (PTZ-431W) working but if i change Tablet Area Mapping values manually i get "Preferences Error"
If i copy and paste this values no error.

**Comment by thenickdude** [comment]
Thanks for the report, I'm currently working on fixing this and you can subscribe to #46 for updates.

**Comment by thenickdude** [comment]
Actually this looks like it may be a distinct bug, so I'm reopening this issue.

**Comment by thenickdude** [comment]
I've fixed this problem now and I'll include that fix in my next release, which should be in a couple of days.

**Comment by yucelyilmazvfx** [comment]
Thanks for fixing this issue! Waiting for the release.

**Comment by thenickdude** [comment]
This should be fixed in my newest release now!
