### ISSUE TITLE
Crash when changing screen mapping monitor index in CTL-470 bamboo

### ISSUE THREAD

**Issue by GiulioBen** [thenickdude/wacom-driver-fix#50]
Thank you for your great work!!

now my old bamboo is working again.

However I have 2 monitors and I'm no more able to map the tablet in the second one... at the moment it covers both the screens...

Do you have any tip to allow me to select only the second screen? I tried editing the xml config file but with no results...

thank you again!

**Comment by thenickdude** [comment]
It looks like the Mapping settings in Wacom Preferences are a little touchy. First click All Screens (even if it already appears selected) then click OK:

<img width="685" alt="Screen Shot 2020-11-07 at 3 16 51 PM" src="https://user-images.githubusercontent.com/1921411/98429578-538ce980-210c-11eb-9640-bda49ee4302c.png">

Then reenter the Mapping settings and you should be able to select Monitor and set it to 2:

<img width="686" alt="Screen Shot 2020-11-07 at 3 17 00 PM" src="https://user-images.githubusercontent.com/1921411/98429583-5a1b6100-210c-11eb-8e40-810d7e23888f.png">

It looks like there is a bug where if the mapping is currently set to a monitor, like monitor 1, attempting to directly change it to monitor 2 causes the preferences to crash, but doing it like this instead by selecting All Screens first avoids the issue.

**Comment by GiulioBen** [comment]
But is the wacom setting available in preferencss with Catalina?

I can't fint id anymore since the update!

**Comment by thenickdude** [comment]
If you installed a system update, they tend to remove the preference pane automatically as Incompatible Software (I have a fix for this queued up at the moment). You need to run the installer again to bring it back.
