### ISSUE TITLE
Mention Intuos 4

### ISSUE THREAD

**Issue by mk12** [thenickdude/wacom-driver-fix#57]
Today I tried using my Intuos 4 Medium tablet on macOS 10.15.7, having not used it for many years.

I installed drivers with `brew cask install wacom-tablet`. This gave me 6.3.41-2, the same version the Wacom website recommends for Intuos 4 on macOS. However, in the preferences I got the same problem described in the README:

> "Waiting for synchronization", then finally "There is a problem with your tablet driver. Please reboot your system. If the problem persists reinstall or update the driver".

I tried everything in https://www.wacom.com/en-us/support?guideId=015-916 and it still wouldn't work. I checked Console and found that WacomTabletDriver was crashing every few minutes:

```
Process:               WacomTabletDriver [2113]
Path:                  /Applications/Wacom Tablet.localized/*/WacomTabletDriver.app/Contents/MacOS/WacomTabletDriver
Identifier:            com.wacom.wacomtablet
Version:               Wacom Tablet 6.3.41-2 (6.3.41f2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WacomTabletDriver [2113]
User ID:               501

Date/Time:             2020-12-15 00:04:16.041 -0500
OS Version:            Mac OS X 10.15.7 (19H114)
Report Version:        12


Time Awake Since Boot: 1000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2113]

VM Regions Near 0x10:
--> 
    __TEXT                 000000010bbcc000-000000010c26f000 [ 6796K] r-x/rwx SM=COW  /Applications/Wacom Tablet.localized/*/WacomTabletDriver.app/Contents/MacOS/WacomTabletDriver

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.wacom.wacomtablet         	0x000000010bfd7222 COnScreenControlData::SaveSettings(ESettingsType) const + 58
1   com.wacom.wacomtablet         	0x000000010bfdb24a COnScreenPanelData::SaveSettings(ESettingsType) const + 884
2   com.wacom.wacomtablet         	0x000000010bfe3ea2 COnScreenPanelsInterface::SaveSettings(ESettingsType) + 226
3   com.wacom.wacomtablet         	0x000000010bf01c4a CWinInterface::SaveSettings(ESettingsType) + 70
4   com.wacom.wacomtablet         	0x000000010bea68cb CTabletDriver::SaveSettings(ESettingsType) + 255
5   com.wacom.wacomtablet         	0x000000010bea66d7 CTabletDriver::SaveSettings(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ESettingsType) + 125
6   com.wacom.wacomtablet         	0x000000010bea34a0 CTabletDriver::SavePrefs(bool) + 124
...
```

I came across this project, and was disappointed to not find Intuos 4 listed. I tried the Intuos 3 manual install instructions anyway. The cursor started moving proportionally with the pen, but the preferences for the "Functions" and "Grip Pen" were all blank. I knew it was probably a bad idea anyway to be using Intuos 3 drivers for Intuos 4.

What finally solved it was deleting *all* Wacom-related files before reinstalling drivers. I had done `brew cask rm wacom-tablet && brew cask install wacom-tablet` several times already, but this time I did the following in between:

* `mdfind -name wacom` and deleted everything that wasn't browser cache/email/crash reports
* `cd /Library && fd -i wacom` (using https://github.com/sharkdp/fd) and deleted everything.
* deleted /Library/Extensions/TabletDriverCFPlugin.bundle

I'm not sure if all were necessary, but after deleting this stuff (must have been leftover from the old installation many years ago), redoing `brew cask install wacom-tablet`, and granting Accessiblity/Input Monitoring permissions, it works!

I'm posting this so that anyone else searching for "Intuos 4" here will find it. It might also be worth adding a section to the README saying that there is no patch for Intuos 4 because a clean install of its official drivers works correctly.

**Comment by thenickdude** [comment]
My 6.3.15-3 driver incidentally fully supports Intuos 4, since support for Intuos 4 tablets was first added in Wacom driver version 6.1.6-4.

When you followed my manual instructions on top of Wacom's 6.3.41-2, you would have ended up with a weird blend of Wacom's official driver 6.3.41-2 and a handful of fixed files from my 6.3.15-3 version, which would have caused your preference pane issues for sure. If you remove all of that using Wacom Utility's uninstaller feature, and just use my automatic installer for 6.3.15-2, you'll get a consistent installation and the preference pane should work fine.

I doubt there is any reason to prefer my older driver over the official unmodified newer one for the Intuos 4 series of tablets. It's true that Wacom's instructions for fixing the tablet permissions are not very comprehensive.
