### ISSUE TITLE
CTE-430

### ISSUE THREAD

**Issue by gosugimoto** [thenickdude/wacom-driver-fix#58]
Who would've thought I could maybe start using this again.  I tried to install the driver, but I get a "A supported tablet was not found on the system."

I can use it and the computer responds, but not in the correct way - not mapping the tablet area to screen or anything else.. Would love to use it, I'm on mac 10.15.6 catalina

Thanks!!!

**Comment by thenickdude** [comment]
Did you follow the instructions to fix up your permissions?

**Comment by gosugimoto** [comment]
Yea and did all the settings in the system preferences.  :(

**Comment by thenickdude** [comment]
Did the entries appear in Input Monitoring and Accessibility for you successfully?

**Comment by gosugimoto** [comment]
I had to do some manila things as I found in one of the solutions in the
issues or Reddit pages...but that didn't work for me either. Perhaps need
to restart again from scratch?

**Comment by thenickdude** [comment]
Yeah if you remove all the permissions from Input Monitoring and Accessibility and restart, hopefully it will pop up and ask you to tick Input Monitoring for PenTabletSpringboard. Then after ticking that you need one more restart before it will ask for Accessibility.

If it never appears in Input Monitoring, try open up the "Terminal" app, and paste this line in there and press enter:

    launchctl load -w /Library/LaunchAgents/com.wacom.pentablet.plist

That may make it fire into life.

**Comment by gosugimoto** [comment]
Not sure what it was, but tried a re-install and now working!! Thank you so
much for reviving an old tech I would've otherwise pawned off for a few
quid.

Thanks!!!
--
iamgo.net

**Comment by thenickdude** [comment]
No problem!
