### ISSUE TITLE
Preferences Error After Loading Wacom CTH-470 driver on High Sierra

### ISSUE THREAD

**Issue by ellejaysee** [thenickdude/wacom-driver-fix#61]
Hi thenickdude. 

I purchased a Late 2009 27" iMac as a dedicated scanner station for a hobby. I will not be updating the operating system past High Sierra. I was able to an archived driver (WacomTablet_608-2) from the Wacom site, but when I click on the Bamboo button under System Preferences, I get the error "Preferences Error - Could not load Bamboo preferences pane.)The driver works, but I cannot adjust the settings.

I went to security and looked for the option to allow access under the Privacy tab (as in Mojave) but this option doesn't seem to exist in High Sierra. 

Any help is appreciated.

**Comment by thenickdude** [comment]
Use my fixed 5.3.7-6 driver instead of that official Wacom version, it should work fine on High Sierra.
