### ISSUE TITLE
Intuos draw ctl-490

### ISSUE THREAD

**Issue by ferferc** [thenickdude/wacom-driver-fix#65]
Hi @thenickdude first of all, thank you for the work you do.
I wanna ask you if some of your wacom patches work for my model wacom Intuos Draw CTL-490 because I installed the one for Intuos 3 but didn't work. I'll hope you can help me, because my mac with Catalina OS didn't recognize my tablet.
Thank you.

**Comment by thenickdude** [comment]
The CTL-490 is still supported by Wacom's newest driver, so you should just be able to use their official driver. It isn't supported by my Intuos 3 v6.3.15-3 driver, sorry!

**Comment by sermelipharo** [comment]
https://cdn.wacom.com/u/productsupport/drivers/mac/professional/releasenotes/Mac_6.4.12-3.html — no longer supported, i wonder if it's possible to implement via yours driver? .10 version has major bug making it impossible to use on 26.1
https://cdn.wacom.com/u/productsupport/drivers/mac/professional/releasenotes/Mac_6.4.10-3.html
