### ISSUE TITLE
Intuos 1 (GD-0608) on Mac M1 Monterey: I can move the cursor but I can't click 

### ISSUE THREAD

**Issue by solares** [thenickdude/wacom-driver-fix#85]
However, I see pressure in the Wacom preferences when I push the tip to the tablet - so the mechanics are definitely working, the OS just ignores these taps. 

![Screen Shot 2022-02-21 at 2 22 39 PM](https://user-images.githubusercontent.com/7260494/154900135-c7b1a79f-1b00-4915-ad04-3449b05409bc.png)

**Comment by thenickdude** [comment]
That'd have to be a problem with the Accessibility permission, try deleting it using the minus button and reboot, then re-tick the entry that reappears for you when you use the pen, and reboot one more time.

**Comment by solares** [comment]
Thanks very much! That did it. 

I ticked both com.wacom.IOManager.app and WacomTabletSpringboard.app. 

![](https://user-images.githubusercontent.com/7260494/154941650-dda8df4e-f29c-4e69-a195-f2d00482710e.png)

Didn't need the last reboot.
