### ISSUE TITLE
Huion H420x cursor in corner MACOS

### ISSUE THREAD

**Issue by usmanahad** [thenickdude/wacom-driver-fix#96]
I don't know why but whenever I use my Huion tablet without the driver, it doesn't draw anything (the cursor moves fine, but it doesn't do anything; it just hovers). If I use my tablet with the driver, the cursor gets stuck in the top left corner and just stays there. The things I've tried are:

- Restart my MacBook
-  Reinstall the driver
- I tried changing the drawing area on my screen (it doesn't do that; it just stays in the corner: only 1 pixel)

I've been at it for an hour now to no success. If you can help me, that'd be great!

**Comment by thenickdude** [comment]
My driver is for Wacom tablets only
