### ISSUE TITLE
Testing on GD-0608-U USB,  Monterey 12.6.1 - WORKING

### ISSUE THREAD

**Issue by FRAMCHEZ** [thenickdude/wacom-driver-fix#99]
Clean MacOS Monterey 12.6.1 install
Installed driver WacomTablet_6.3.44-2.dmg  from wacom support website (this is the 1st - oldest driver for Monterey)
(tried first WacomTablet_6.1.6-4.dmg, but not compatible with Monterey)
Installed Install-Wacom-Tablet-6.1.6-4-patched.pkg 
All OK, working. thanks a lot, love my wacom, and love you.

**Comment by thenickdude** [comment]
Great!
